-- +migrate Up
CREATE TABLE users
(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

PRIMARY KEY (id),
UNIQUE KEY users_username_unique (username)
) DEFAULT CHARACTER SET utf8, DEFAULT COLLATE utf8_unicode_ci;

-- +migrate Down
DROP TABLE users;

